"""empty message

Revision ID: 394972232a36
Revises: 
Create Date: 2022-04-19 19:59:49.509704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394972232a36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battleDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YourPokemon', sa.String(length=100), nullable=True),
    sa.Column('OpponentsPokemon', sa.String(length=100), nullable=True),
    sa.Column('Winner', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battleDB')
    # ### end Alembic commands ###
